on:
  pull_request:
    types:
      - opened

jobs:
  if: ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop' && contains(github.event.pull_request.labels.*.name, 'releng') && contains(github.event.pull_request.labels.*.name, 'automerge') }}
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: automerge
        run: gh pr merge $PR_NUMBER --admin --merge --delete-branch
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          PR_NUMBER: "${{ github.event.pull_request.number }}"

