on:
  pull_request:
    types:
      - opened

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: automerge
        run: gh pr merge $PR_NUMBER --admin --merge
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          PR_NUMBER: "${{ github.event.pull_request.number }}"

