on:
  push:

jobs:
  make_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: create pr
        run: gh pr create --base develop --head main --title "TODO" --body "todo"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"

