---
name: following

on:
  workflow_call:
    secrets:
      PASSWORD:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - run: echo ${{ env.SHA }}
        env:
          SHA: ${{ github.sha }}
      - run: echo ${{ env.PASSWORD }}
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
