---
name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - run: exit 0
  call-workflow:
    needs: [test]
    if: ${{ github.ref_type == 'tag' }}
    uses: ./.github/workflows/following.yml

