on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - run: echo
        env: echo ${{ env.REF }}
          REF: "${{ github.ref_type }}"

